// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "rpm/microservices/api/graph/model"
)

// ProductCatalogResolver is an autogenerated mock type for the ProductCatalogResolver type
type ProductCatalogResolver struct {
	mock.Mock
}

// GetProductCatalog provides a mock function with given fields: ctx, obj
func (_m *ProductCatalogResolver) GetProductCatalog(ctx context.Context, obj *model.AbstractModel) (*model.Catalogs, error) {
	ret := _m.Called(ctx, obj)

	var r0 *model.Catalogs
	if rf, ok := ret.Get(0).(func(context.Context, *model.AbstractModel) *model.Catalogs); ok {
		r0 = rf(ctx, obj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Catalogs)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *model.AbstractModel) error); ok {
		r1 = rf(ctx, obj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
