// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "rpm/microservices/api/graph/model"
)

// ShoppingCartResolver is an autogenerated mock type for the ShoppingCartResolver type
type ShoppingCartResolver struct {
	mock.Mock
}

// GetShoppingCartByUserID provides a mock function with given fields: ctx, obj, userID
func (_m *ShoppingCartResolver) GetShoppingCartByUserID(ctx context.Context, obj *model.AbstractModel, userID string) (*model.Carts, error) {
	ret := _m.Called(ctx, obj, userID)

	var r0 *model.Carts
	if rf, ok := ret.Get(0).(func(context.Context, *model.AbstractModel, string) *model.Carts); ok {
		r0 = rf(ctx, obj, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Carts)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *model.AbstractModel, string) error); ok {
		r1 = rf(ctx, obj, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
