// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "rpm/microservices/api/graph/model"
)

// UserResolver is an autogenerated mock type for the UserResolver type
type UserResolver struct {
	mock.Mock
}

// GetUserInfoByID provides a mock function with given fields: ctx, obj, userID
func (_m *UserResolver) GetUserInfoByID(ctx context.Context, obj *model.AbstractModel, userID string) (*model.UserInfo, error) {
	ret := _m.Called(ctx, obj, userID)

	var r0 *model.UserInfo
	if rf, ok := ret.Get(0).(func(context.Context, *model.AbstractModel, string) *model.UserInfo); ok {
		r0 = rf(ctx, obj, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *model.AbstractModel, string) error); ok {
		r1 = rf(ctx, obj, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListOfUser provides a mock function with given fields: ctx, obj
func (_m *UserResolver) ListOfUser(ctx context.Context, obj *model.AbstractModel) (*model.ListUser, error) {
	ret := _m.Called(ctx, obj)

	var r0 *model.ListUser
	if rf, ok := ret.Get(0).(func(context.Context, *model.AbstractModel) *model.ListUser); ok {
		r0 = rf(ctx, obj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ListUser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *model.AbstractModel) error); ok {
		r1 = rf(ctx, obj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
