// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/cart.proto

package go_micro_srv_core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShoppingCartResponse struct {
	Cart                 *Cart    `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShoppingCartResponse) Reset()         { *m = ShoppingCartResponse{} }
func (m *ShoppingCartResponse) String() string { return proto.CompactTextString(m) }
func (*ShoppingCartResponse) ProtoMessage()    {}
func (*ShoppingCartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1520582f7a6ef1d6, []int{0}
}

func (m *ShoppingCartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShoppingCartResponse.Unmarshal(m, b)
}
func (m *ShoppingCartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShoppingCartResponse.Marshal(b, m, deterministic)
}
func (m *ShoppingCartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShoppingCartResponse.Merge(m, src)
}
func (m *ShoppingCartResponse) XXX_Size() int {
	return xxx_messageInfo_ShoppingCartResponse.Size(m)
}
func (m *ShoppingCartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShoppingCartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShoppingCartResponse proto.InternalMessageInfo

func (m *ShoppingCartResponse) GetCart() *Cart {
	if m != nil {
		return m.Cart
	}
	return nil
}

type Cart struct {
	UserInfo             *UserInfoResponse `protobuf:"bytes,1,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	ProductCart          []*ProductCart    `protobuf:"bytes,2,rep,name=productCart,proto3" json:"productCart,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Cart) Reset()         { *m = Cart{} }
func (m *Cart) String() string { return proto.CompactTextString(m) }
func (*Cart) ProtoMessage()    {}
func (*Cart) Descriptor() ([]byte, []int) {
	return fileDescriptor_1520582f7a6ef1d6, []int{1}
}

func (m *Cart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cart.Unmarshal(m, b)
}
func (m *Cart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cart.Marshal(b, m, deterministic)
}
func (m *Cart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cart.Merge(m, src)
}
func (m *Cart) XXX_Size() int {
	return xxx_messageInfo_Cart.Size(m)
}
func (m *Cart) XXX_DiscardUnknown() {
	xxx_messageInfo_Cart.DiscardUnknown(m)
}

var xxx_messageInfo_Cart proto.InternalMessageInfo

func (m *Cart) GetUserInfo() *UserInfoResponse {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *Cart) GetProductCart() []*ProductCart {
	if m != nil {
		return m.ProductCart
	}
	return nil
}

type ProductCart struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Quantity             int32    `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductCart) Reset()         { *m = ProductCart{} }
func (m *ProductCart) String() string { return proto.CompactTextString(m) }
func (*ProductCart) ProtoMessage()    {}
func (*ProductCart) Descriptor() ([]byte, []int) {
	return fileDescriptor_1520582f7a6ef1d6, []int{2}
}

func (m *ProductCart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductCart.Unmarshal(m, b)
}
func (m *ProductCart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductCart.Marshal(b, m, deterministic)
}
func (m *ProductCart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductCart.Merge(m, src)
}
func (m *ProductCart) XXX_Size() int {
	return xxx_messageInfo_ProductCart.Size(m)
}
func (m *ProductCart) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductCart.DiscardUnknown(m)
}

var xxx_messageInfo_ProductCart proto.InternalMessageInfo

func (m *ProductCart) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *ProductCart) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func init() {
	proto.RegisterType((*ShoppingCartResponse)(nil), "go.micro.srv.core.ShoppingCartResponse")
	proto.RegisterType((*Cart)(nil), "go.micro.srv.core.Cart")
	proto.RegisterType((*ProductCart)(nil), "go.micro.srv.core.ProductCart")
}

func init() {
	proto.RegisterFile("proto/cart.proto", fileDescriptor_1520582f7a6ef1d6)
}

var fileDescriptor_1520582f7a6ef1d6 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xed, 0xba, 0xea, 0x32, 0xf5, 0xa0, 0x41, 0xd8, 0xd2, 0x83, 0x94, 0x7a, 0xb0, 0x20,
	0x44, 0xa8, 0xde, 0x15, 0x7b, 0x10, 0x6f, 0x12, 0xf1, 0x2c, 0xb5, 0x8d, 0x6b, 0x0f, 0x76, 0xb2,
	0x93, 0xa9, 0xb0, 0x3f, 0xc1, 0x7f, 0x2d, 0x8d, 0xed, 0x5a, 0x30, 0xde, 0x32, 0x79, 0xdf, 0x7b,
	0x99, 0xcc, 0xc0, 0x91, 0x21, 0x64, 0xbc, 0xac, 0x4a, 0x62, 0xe9, 0x8e, 0xe2, 0x78, 0x85, 0xf2,
	0xa3, 0xa9, 0x08, 0xa5, 0xa5, 0x4f, 0x59, 0x21, 0xe9, 0x78, 0x84, 0x90, 0xf4, 0x0f, 0x94, 0x16,
	0x70, 0xf2, 0xf4, 0x8e, 0xc6, 0x34, 0xed, 0xaa, 0x28, 0x89, 0x95, 0xb6, 0x06, 0x5b, 0xab, 0xc5,
	0x05, 0xcc, 0xfb, 0xa8, 0x28, 0x48, 0x82, 0x2c, 0xcc, 0x97, 0xf2, 0x4f, 0x96, 0x74, 0xb8, 0x83,
	0xd2, 0xaf, 0x00, 0xe6, 0x7d, 0x29, 0x6e, 0x60, 0xd1, 0x59, 0x4d, 0x0f, 0xed, 0x1b, 0x0e, 0xce,
	0x33, 0x8f, 0xf3, 0x79, 0x40, 0xc6, 0xc7, 0xd4, 0xd6, 0x24, 0x6e, 0x21, 0x34, 0x84, 0x75, 0x57,
	0x71, 0x9f, 0x17, 0xcd, 0x92, 0xdd, 0x2c, 0xcc, 0x4f, 0x3d, 0x19, 0x8f, 0xbf, 0x94, 0x9a, 0x5a,
	0xd2, 0x17, 0x08, 0x27, 0x9a, 0xb8, 0x86, 0x83, 0x41, 0x1d, 0x1a, 0x8a, 0xff, 0x0f, 0x53, 0x23,
	0x2a, 0x62, 0x58, 0xac, 0xbb, 0xb2, 0xe5, 0x86, 0x37, 0xd1, 0x2c, 0x09, 0xb2, 0x3d, 0xb5, 0xad,
	0x73, 0x86, 0xc3, 0xe9, 0xc4, 0x44, 0x0d, 0xcb, 0x7b, 0xcd, 0xd3, 0xab, 0xbb, 0x8d, 0xfb, 0x61,
	0x2d, 0x7c, 0x8d, 0x17, 0x48, 0x5a, 0xe9, 0x75, 0xa7, 0x2d, 0xc7, 0xe7, 0x1e, 0xdd, 0xb7, 0x8d,
	0x74, 0xe7, 0x75, 0xdf, 0xad, 0xeb, 0xea, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x21, 0xd1, 0x66, 0x0f,
	0xe7, 0x01, 0x00, 0x00,
}
