// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/cart.proto

package go_micro_srv_core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ShoppingCart service

func NewShoppingCartEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ShoppingCart service

type ShoppingCartService interface {
	GetShoppingCartByUserId(ctx context.Context, in *CoreRequest, opts ...client.CallOption) (*ShoppingCartResponse, error)
}

type shoppingCartService struct {
	c    client.Client
	name string
}

func NewShoppingCartService(name string, c client.Client) ShoppingCartService {
	return &shoppingCartService{
		c:    c,
		name: name,
	}
}

func (c *shoppingCartService) GetShoppingCartByUserId(ctx context.Context, in *CoreRequest, opts ...client.CallOption) (*ShoppingCartResponse, error) {
	req := c.c.NewRequest(c.name, "ShoppingCart.GetShoppingCartByUserId", in)
	out := new(ShoppingCartResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ShoppingCart service

type ShoppingCartHandler interface {
	GetShoppingCartByUserId(context.Context, *CoreRequest, *ShoppingCartResponse) error
}

func RegisterShoppingCartHandler(s server.Server, hdlr ShoppingCartHandler, opts ...server.HandlerOption) error {
	type shoppingCart interface {
		GetShoppingCartByUserId(ctx context.Context, in *CoreRequest, out *ShoppingCartResponse) error
	}
	type ShoppingCart struct {
		shoppingCart
	}
	h := &shoppingCartHandler{hdlr}
	return s.Handle(s.NewHandler(&ShoppingCart{h}, opts...))
}

type shoppingCartHandler struct {
	ShoppingCartHandler
}

func (h *shoppingCartHandler) GetShoppingCartByUserId(ctx context.Context, in *CoreRequest, out *ShoppingCartResponse) error {
	return h.ShoppingCartHandler.GetShoppingCartByUserId(ctx, in, out)
}
