// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/catalog.proto

package go_micro_srv_core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ProductCatalog service

func NewProductCatalogEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ProductCatalog service

type ProductCatalogService interface {
	GetProductCatalog(ctx context.Context, in *CoreRequest, opts ...client.CallOption) (*ProductCatalogResponse, error)
}

type productCatalogService struct {
	c    client.Client
	name string
}

func NewProductCatalogService(name string, c client.Client) ProductCatalogService {
	return &productCatalogService{
		c:    c,
		name: name,
	}
}

func (c *productCatalogService) GetProductCatalog(ctx context.Context, in *CoreRequest, opts ...client.CallOption) (*ProductCatalogResponse, error) {
	req := c.c.NewRequest(c.name, "ProductCatalog.GetProductCatalog", in)
	out := new(ProductCatalogResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProductCatalog service

type ProductCatalogHandler interface {
	GetProductCatalog(context.Context, *CoreRequest, *ProductCatalogResponse) error
}

func RegisterProductCatalogHandler(s server.Server, hdlr ProductCatalogHandler, opts ...server.HandlerOption) error {
	type productCatalog interface {
		GetProductCatalog(ctx context.Context, in *CoreRequest, out *ProductCatalogResponse) error
	}
	type ProductCatalog struct {
		productCatalog
	}
	h := &productCatalogHandler{hdlr}
	return s.Handle(s.NewHandler(&ProductCatalog{h}, opts...))
}

type productCatalogHandler struct {
	ProductCatalogHandler
}

func (h *productCatalogHandler) GetProductCatalog(ctx context.Context, in *CoreRequest, out *ProductCatalogResponse) error {
	return h.ProductCatalogHandler.GetProductCatalog(ctx, in, out)
}
