// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/catalog.proto

package go_micro_srv_core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProductCatalogResponse struct {
	Catalogs             *Catalog `protobuf:"bytes,1,opt,name=catalogs,proto3" json:"catalogs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductCatalogResponse) Reset()         { *m = ProductCatalogResponse{} }
func (m *ProductCatalogResponse) String() string { return proto.CompactTextString(m) }
func (*ProductCatalogResponse) ProtoMessage()    {}
func (*ProductCatalogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1de9eeb3bc14aad2, []int{0}
}

func (m *ProductCatalogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductCatalogResponse.Unmarshal(m, b)
}
func (m *ProductCatalogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductCatalogResponse.Marshal(b, m, deterministic)
}
func (m *ProductCatalogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductCatalogResponse.Merge(m, src)
}
func (m *ProductCatalogResponse) XXX_Size() int {
	return xxx_messageInfo_ProductCatalogResponse.Size(m)
}
func (m *ProductCatalogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductCatalogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProductCatalogResponse proto.InternalMessageInfo

func (m *ProductCatalogResponse) GetCatalogs() *Catalog {
	if m != nil {
		return m.Catalogs
	}
	return nil
}

type Catalog struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Catalog) Reset()         { *m = Catalog{} }
func (m *Catalog) String() string { return proto.CompactTextString(m) }
func (*Catalog) ProtoMessage()    {}
func (*Catalog) Descriptor() ([]byte, []int) {
	return fileDescriptor_1de9eeb3bc14aad2, []int{1}
}

func (m *Catalog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Catalog.Unmarshal(m, b)
}
func (m *Catalog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Catalog.Marshal(b, m, deterministic)
}
func (m *Catalog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Catalog.Merge(m, src)
}
func (m *Catalog) XXX_Size() int {
	return xxx_messageInfo_Catalog.Size(m)
}
func (m *Catalog) XXX_DiscardUnknown() {
	xxx_messageInfo_Catalog.DiscardUnknown(m)
}

var xxx_messageInfo_Catalog proto.InternalMessageInfo

func (m *Catalog) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func init() {
	proto.RegisterType((*ProductCatalogResponse)(nil), "go.micro.srv.core.ProductCatalogResponse")
	proto.RegisterType((*Catalog)(nil), "go.micro.srv.core.Catalog")
}

func init() {
	proto.RegisterFile("proto/catalog.proto", fileDescriptor_1de9eeb3bc14aad2)
}

var fileDescriptor_1de9eeb3bc14aad2 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4e, 0x2c, 0x49, 0xcc, 0xc9, 0x4f, 0xd7, 0x03, 0xf3, 0x84, 0x04, 0xd3, 0xf3,
	0xf5, 0x72, 0x33, 0x93, 0x8b, 0xf2, 0xf5, 0x8a, 0x8b, 0xca, 0xf4, 0x92, 0xf3, 0x8b, 0x52, 0xa5,
	0x04, 0xa0, 0xea, 0xf2, 0x8b, 0x52, 0x21, 0x8a, 0x94, 0x02, 0xb8, 0xc4, 0x02, 0x8a, 0xf2, 0x53,
	0x4a, 0x93, 0x4b, 0x9c, 0x21, 0x9a, 0x83, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xcc,
	0xb8, 0x38, 0xa0, 0xe6, 0x15, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0x49, 0xe9, 0x61, 0x98,
	0xa8, 0x07, 0xd3, 0x05, 0x57, 0xab, 0xe4, 0xc8, 0xc5, 0x0e, 0x15, 0x04, 0x19, 0x51, 0x00, 0x31,
	0x1c, 0x64, 0x04, 0x33, 0x0e, 0x23, 0xa0, 0xf6, 0x07, 0xc1, 0xd5, 0x1a, 0x15, 0x71, 0xf1, 0xa1,
	0x3a, 0x4a, 0x28, 0x81, 0x4b, 0xd0, 0x3d, 0xb5, 0x04, 0x4d, 0x50, 0x0e, 0x9b, 0x7b, 0xf2, 0x8b,
	0x52, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0xa4, 0x34, 0x71, 0x5b, 0x86, 0xe6, 0x59, 0x25,
	0x86, 0x24, 0x36, 0x70, 0x78, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xae, 0xb6, 0x15, 0xf7,
	0x4b, 0x01, 0x00, 0x00,
}
