// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/core.proto

package go_micro_srv_core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CoreRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoreRequest) Reset()         { *m = CoreRequest{} }
func (m *CoreRequest) String() string { return proto.CompactTextString(m) }
func (*CoreRequest) ProtoMessage()    {}
func (*CoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4b0acae2797acdd, []int{0}
}

func (m *CoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoreRequest.Unmarshal(m, b)
}
func (m *CoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoreRequest.Marshal(b, m, deterministic)
}
func (m *CoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoreRequest.Merge(m, src)
}
func (m *CoreRequest) XXX_Size() int {
	return xxx_messageInfo_CoreRequest.Size(m)
}
func (m *CoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CoreRequest proto.InternalMessageInfo

func (m *CoreRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type Product struct {
	ProductName          string   `protobuf:"bytes,1,opt,name=productName,proto3" json:"productName,omitempty"`
	ProductDescription   string   `protobuf:"bytes,2,opt,name=productDescription,proto3" json:"productDescription,omitempty"`
	Price                int32    `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Stock                int32    `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4b0acae2797acdd, []int{1}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *Product) GetProductDescription() string {
	if m != nil {
		return m.ProductDescription
	}
	return ""
}

func (m *Product) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetStock() int32 {
	if m != nil {
		return m.Stock
	}
	return 0
}

type UserInfoResponse struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	UserLocation         string   `protobuf:"bytes,3,opt,name=userLocation,proto3" json:"userLocation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoResponse) Reset()         { *m = UserInfoResponse{} }
func (m *UserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*UserInfoResponse) ProtoMessage()    {}
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4b0acae2797acdd, []int{2}
}

func (m *UserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoResponse.Unmarshal(m, b)
}
func (m *UserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoResponse.Marshal(b, m, deterministic)
}
func (m *UserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoResponse.Merge(m, src)
}
func (m *UserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_UserInfoResponse.Size(m)
}
func (m *UserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoResponse proto.InternalMessageInfo

func (m *UserInfoResponse) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UserInfoResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInfoResponse) GetUserLocation() string {
	if m != nil {
		return m.UserLocation
	}
	return ""
}

func init() {
	proto.RegisterType((*CoreRequest)(nil), "go.micro.srv.core.CoreRequest")
	proto.RegisterType((*Product)(nil), "go.micro.srv.core.Product")
	proto.RegisterType((*UserInfoResponse)(nil), "go.micro.srv.core.UserInfoResponse")
}

func init() {
	proto.RegisterFile("proto/core.proto", fileDescriptor_a4b0acae2797acdd)
}

var fileDescriptor_a4b0acae2797acdd = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4a, 0x04, 0x31,
	0x10, 0x45, 0x89, 0xe3, 0x8c, 0x5a, 0xe3, 0x62, 0x2c, 0x44, 0x82, 0xab, 0x26, 0x20, 0xcc, 0x2a,
	0x2e, 0x3c, 0x82, 0xb3, 0x11, 0x44, 0x24, 0xe0, 0x01, 0xda, 0x58, 0x4a, 0x94, 0xee, 0x8a, 0x95,
	0xb4, 0x57, 0xf0, 0xda, 0x92, 0xa4, 0x11, 0x05, 0xdd, 0xfd, 0xf7, 0x7f, 0x41, 0x1e, 0x81, 0x4d,
	0x14, 0xce, 0x7c, 0xe9, 0x59, 0xc8, 0xd6, 0x88, 0x27, 0x2f, 0x6c, 0x87, 0xe0, 0x85, 0x6d, 0x92,
	0x0f, 0x5b, 0x06, 0x73, 0x01, 0xeb, 0x6b, 0x16, 0x72, 0xf4, 0x3e, 0x51, 0xca, 0x78, 0x06, 0xab,
	0x29, 0x91, 0xdc, 0xec, 0xb4, 0xea, 0xd4, 0xf6, 0xc8, 0xcd, 0x64, 0x3e, 0x15, 0x1c, 0xdc, 0x0b,
	0x3f, 0x4d, 0x3e, 0x63, 0x07, 0xeb, 0xd8, 0xe2, 0x5d, 0x3f, 0xd0, 0x7c, 0xf8, 0xb3, 0x42, 0x0b,
	0x38, 0xe3, 0x8e, 0x92, 0x97, 0x10, 0x73, 0xe0, 0x51, 0xef, 0xd5, 0xc3, 0x3f, 0x16, 0x3c, 0x85,
	0x65, 0x94, 0xe0, 0x49, 0x2f, 0x3a, 0xb5, 0x5d, 0xba, 0x06, 0xa5, 0x4d, 0x99, 0xfd, 0x9b, 0xde,
	0x6f, 0x6d, 0x05, 0xf3, 0x0a, 0x9b, 0x87, 0xe2, 0x34, 0x3e, 0xb3, 0xa3, 0x14, 0x79, 0x4c, 0xf4,
	0x9f, 0x35, 0x9e, 0xc3, 0x61, 0x49, 0x55, 0xb3, 0xbd, 0xfe, 0xcd, 0x68, 0xe0, 0xb8, 0xe4, 0x5b,
	0xf6, 0x7d, 0xb5, 0x5b, 0xd4, 0xfd, 0x57, 0xf7, 0xb8, 0xaa, 0xdf, 0x76, 0xf5, 0x15, 0x00, 0x00,
	0xff, 0xff, 0xbf, 0xcd, 0xd6, 0xf7, 0x4a, 0x01, 0x00, 0x00,
}
