// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	go_micro_srv_core "rpm/microservices/core/proto"

	mock "github.com/stretchr/testify/mock"
)

// CatalogUseCase is an autogenerated mock type for the CatalogUseCase type
type CatalogUseCase struct {
	mock.Mock
}

// GetProductCatalog provides a mock function with given fields:
func (_m *CatalogUseCase) GetProductCatalog() (*go_micro_srv_core.ProductCatalogResponse, error) {
	ret := _m.Called()

	var r0 *go_micro_srv_core.ProductCatalogResponse
	if rf, ok := ret.Get(0).(func() *go_micro_srv_core.ProductCatalogResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*go_micro_srv_core.ProductCatalogResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
