// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	model "rpm/microservices/core/model"

	mock "github.com/stretchr/testify/mock"
)

// Config is an autogenerated mock type for the Config type
type Config struct {
	mock.Mock
}

// GetApplicationConfig provides a mock function with given fields:
func (_m *Config) GetApplicationConfig() *model.ApplicationConfig {
	ret := _m.Called()

	var r0 *model.ApplicationConfig
	if rf, ok := ret.Get(0).(func() *model.ApplicationConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ApplicationConfig)
		}
	}

	return r0
}
