// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/micro/go-micro/v2/client"

	go_micro_srv_core "rpm/microservices/core/proto"

	mock "github.com/stretchr/testify/mock"
)

// ProductCatalogService is an autogenerated mock type for the ProductCatalogService type
type ProductCatalogService struct {
	mock.Mock
}

// GetProductCatalog provides a mock function with given fields: ctx, in, opts
func (_m *ProductCatalogService) GetProductCatalog(ctx context.Context, in *go_micro_srv_core.CoreRequest, opts ...client.CallOption) (*go_micro_srv_core.ProductCatalogResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *go_micro_srv_core.ProductCatalogResponse
	if rf, ok := ret.Get(0).(func(context.Context, *go_micro_srv_core.CoreRequest, ...client.CallOption) *go_micro_srv_core.ProductCatalogResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*go_micro_srv_core.ProductCatalogResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *go_micro_srv_core.CoreRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
