// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/micro/go-micro/v2/client"

	go_micro_srv_core "rpm/microservices/core/proto"

	mock "github.com/stretchr/testify/mock"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// GetUserById provides a mock function with given fields: ctx, in, opts
func (_m *UserService) GetUserById(ctx context.Context, in *go_micro_srv_core.CoreRequest, opts ...client.CallOption) (*go_micro_srv_core.UserInfoResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *go_micro_srv_core.UserInfoResponse
	if rf, ok := ret.Get(0).(func(context.Context, *go_micro_srv_core.CoreRequest, ...client.CallOption) *go_micro_srv_core.UserInfoResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*go_micro_srv_core.UserInfoResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *go_micro_srv_core.CoreRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListOfUser provides a mock function with given fields: ctx, in, opts
func (_m *UserService) ListOfUser(ctx context.Context, in *go_micro_srv_core.CoreRequest, opts ...client.CallOption) (*go_micro_srv_core.ListUserResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *go_micro_srv_core.ListUserResponse
	if rf, ok := ret.Get(0).(func(context.Context, *go_micro_srv_core.CoreRequest, ...client.CallOption) *go_micro_srv_core.ListUserResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*go_micro_srv_core.ListUserResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *go_micro_srv_core.CoreRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
